### ISSUE TITLE
`types_helper::map_insert_operation()` has huge performance impact

### ISSUE THREAD

**Issue by snork-alt** [getdozer/dozer#1028]
calling `types_helper::map_insert_operation(self.api_endpoint.name.clone(), new, id);` in `dozer-orchestrator/src/pipeline/sinks.rs`

with call enabled: ~45k rec/sec
with call disabled: ~90k rec/sec

**Comment by chubei** [comment]
Can you push the version of code with it disabled?

**Comment by chubei** [comment]
Reporting peak performance (reached seconds after the app is started) on my machine:

With code in https://github.com/getdozer/dozer/pull/1068/commits/ad5ba5d72c4433fb0b23753262f64aaf2e476acc, data and config in https://github.com/getdozer/dozer-samples-internal/tree/main/taxi-objectstore, `trips_cache: 23k/s`

With code in https://github.com/chubei/dozer/tree/test/map, same data and config, `trips_cache: 23k/s`.

There's difference, but not that dramatic.
