### ISSUE TITLE
Review the implementation of Data Types support

### ISSUE THREAD

**Issue by mediuminvader** [getdozer/dozer#1228]
## Data Types

- [x] [Specifications for connectors](https://github.com/getdozer/dozer/issues/1228#issuecomment-1465624115) with supported data types 
- [x] [Specifications for operators](https://github.com/getdozer/dozer/issues/1228#issuecomment-1467758132) -> Possible Return types / possible inputs (Would be good  to be able to generate a list by running through all operators and calling a specific method) So we are very clear -> SQL specification
- [x] #1250
- [x] Implement JSON E2E support
- [x] Implement TimeUnit, Duration support
- [x] Implement u128, i128 support
- [x] Integration tests with generated combinations of data types and regression (E2E) -> E2E tests
- [x] A considerable # of handwritten SQL statements (could be copied from somewhere else and adapted) -> SQL unit tests

**Comment by chloeminkyung** [comment]
|                    | **UInt** | **UInt128** | **Int** | **Int128** | **Float** | **Boolean** | **String** | **Text** | **Binary** | **Decimal** | **Timestamp** | **Date** | **Duration** | **Json** | **Point** |
|--------------------|----------|-------------|---------|------------|-----------|-------------|------------|----------|------------|-------------|---------------|----------|--------------|----------|-----------|
| **Postgres**       |          |             | ✅       |            | ✅         | ✅           | ✅          |          | ✅          | ✅           | ✅             | ✅        |              |          | ✅         |
| **Ethereum Log**   | ✅        |             |         |            |           | ✅           | ✅          | ✅        | ✅          |             |               |          |              |          |           |
| **Ethereum Trace** | ✅        |             |         |            |           |             | ✅          | ✅        |            |             |               |          |              |          |           |
| **Snowflake**      |          |             | ✅       |            | ✅         | ✅           | ✅          |          |            | ✅           | ✅             | ✅        |              |          |           |
| **Object Store**   | ✅        |             | ✅       |            | ✅         | ✅           | ✅          | ✅        | ✅          |             | ✅             | ✅        |              |          |           |
| **Debezium**       |          |             | ✅       |            | ✅         | ✅           | ✅          |          | ✅          | ✅           | ✅             | ✅        |              |          |           |
| **gRPC**           | ✅        |             | ✅       |            | ✅         | ✅           | ✅          | ✅        | ✅          |             | ✅             | ✅        |              |          |           |
| **Delta Lake**     | ✅        |             | ✅       |            | ✅         | ✅           | ✅          | ✅        | ✅          |             | ✅             | ✅        |              |          |           |

**Comment by chloeminkyung** [comment]
# Postgres
```
pub fn postgres_type_to_dozer_type(column_type: Type) -> Result<FieldType, PostgresSchemaError> {
    match column_type {
        Type::BOOL => Ok(FieldType::Boolean),
        Type::INT2 | Type::INT4 | Type::INT8 => Ok(FieldType::Int),
        Type::CHAR | Type::TEXT | Type::VARCHAR | Type::BPCHAR => Ok(FieldType::String),
        Type::FLOAT4 | Type::FLOAT8 => Ok(FieldType::Float),
        Type::BIT | Type::BYTEA => Ok(FieldType::Binary),
        Type::TIMESTAMP | Type::TIMESTAMPTZ => Ok(FieldType::Timestamp),
        Type::NUMERIC => Ok(FieldType::Decimal),
        Type::JSONB => Ok(FieldType::Json),
        Type::DATE => Ok(FieldType::Date),
        Type::POINT => Ok(FieldType::Point),
        _ => Err(ColumnTypeNotSupported(column_type.name().to_string())),
    }
}

```

# Ethereum Log
```
fields.push(FieldDefinition {
    name: input.name,
    typ: match input.kind {
        web3::ethabi::ParamType::Address => FieldType::String,
        web3::ethabi::ParamType::Bytes => FieldType::Binary,
        web3::ethabi::ParamType::FixedBytes(_) => FieldType::Binary,
        web3::ethabi::ParamType::Int(_) => FieldType::UInt,
        web3::ethabi::ParamType::Uint(_) => FieldType::UInt,
        web3::ethabi::ParamType::Bool => FieldType::Boolean,
        web3::ethabi::ParamType::String => FieldType::String,
        // TODO: These are to be mapped to appropriate types
        web3::ethabi::ParamType::Array(_)
        | web3::ethabi::ParamType::FixedArray(_, _)
        | web3::ethabi::ParamType::Tuple(_) => FieldType::Text,
    },
    nullable: false,
    source: SourceDefinition::Dynamic,
});

```

# Ethereum Trace
```
let op = Operation::Insert {
    new: Record {
        schema_id: Some(get_schema_id()),
        values: vec![
            Field::String(trace.type_field.clone()),
            Field::String(format!("{:?}", trace.from)),
            Field::String(format!("{:?}", trace.to)),
            Field::UInt(trace.value.unwrap_or(U256::zero()).low_u64()),
            Field::UInt(trace.gas.low_u64()),
            Field::UInt(trace.gas_used.low_u64()),
            Field::Text(format!("{:?}", trace.input)),
            Field::Text(format!("{:?}", trace.output)),
        ],
        version: None,
    },
};

```

# Snowflake
```
pub fn convert_data(
    cursor: &mut Cursor<Executed, AutocommitOn>,
    i: u16,
    column_descriptor: &ColumnDescriptor,
) -> Result<Field, SnowflakeSchemaError> {
    match column_descriptor.data_type {
        SqlDataType::SQL_CHAR | SqlDataType::SQL_VARCHAR => {
            match cursor
                .get_data::<String>(i)
                .map_err(|e| SnowflakeSchemaError::ValueConversionError(Box::new(e)))?
            {
                None => Ok(Field::Null),
                Some(value) => Ok(Field::from(value)),
            }
        }
        SqlDataType::SQL_DECIMAL
        | SqlDataType::SQL_NUMERIC
        | SqlDataType::SQL_INTEGER
        | SqlDataType::SQL_SMALLINT => match column_descriptor.decimal_digits {
            None => {
                match cursor
                    .get_data::<i64>(i)
                    .map_err(|e| SnowflakeSchemaError::ValueConversionError(Box::new(e)))?
                {
                    None => Ok(Field::Null),
                    Some(value) => Ok(Field::from(value)),
                }
            }
            Some(digits) => {
                match cursor
                    .get_data::<&[u8]>(i)
                    .map_err(|e| SnowflakeSchemaError::ValueConversionError(Box::new(e)))?
                {
                    None => Ok(Field::Null),
                    Some(value) => convert_decimal(value, digits),
                }
            }
        },
        SqlDataType::SQL_FLOAT | SqlDataType::SQL_REAL | SqlDataType::SQL_DOUBLE => {
            match cursor
                .get_data::<f64>(i)
                .map_err(|e| SnowflakeSchemaError::ValueConversionError(Box::new(e)))?
            {
                None => Ok(Field::Null),
                Some(value) => Ok(Field::from(value)),
            }
        }
        SqlDataType::SQL_TIMESTAMP => {
            match cursor
                .get_data::<SQL_TIMESTAMP_STRUCT>(i)
                .map_err(|e| SnowflakeSchemaError::ValueConversionError(Box::new(e)))?
            {
                None => Ok(Field::Null),
                Some(value) => {
                    let date = NaiveDate::from_ymd_opt(
                        value.year as i32,
                        value.month as u32,
                        value.day as u32,
                    )
                    .map_or_else(|| Err(InvalidDateError), Ok)?;
                    let time = NaiveTime::from_hms_nano_opt(
                        value.hour as u32,
                        value.minute as u32,
                        value.second as u32,
                        value.fraction,
                    )
                    .map_or_else(|| Err(InvalidTimeError), Ok)?;
                    Ok(Field::from(NaiveDateTime::new(date, time)))
                }
            }
        }
        SqlDataType::SQL_DATE => {
            match cursor
                .get_data::<SQL_DATE_STRUCT>(i)
                .map_err(|e| SnowflakeSchemaError::ValueConversionError(Box::new(e)))?
            {
                None => Ok(Field::Null),
                Some(value) => {
                    let date = NaiveDate::from_ymd_opt(
                        value.year as i32,
                        value.month as u32,
                        value.day as u32,
                    )
                    .map_or_else(|| Err(InvalidDateError), Ok)?;
                    Ok(Field::from(date))
                }
            }
        }
        SqlDataType::SQL_EXT_BIT => {
            match cursor
                .get_data::<bool>(i)
                .map_err(|e| SnowflakeSchemaError::ValueConversionError(Box::new(e)))?
            {
                None => Ok(Field::Null),
                Some(v) => Ok(Field::from(v)),
            }
        }
        _ => Err(SnowflakeSchemaError::ColumnTypeNotSupported(format!(
            "{:?}",
            &column_descriptor.data_type
        ))),
    }
}
```

# Obejct Store
```
pub fn map_schema_to_dozer<'a, I: Iterator<Item = &'a Field>>(
    fields_list: I,
) -> Result<Vec<FieldDefinition>, ObjectStoreSchemaError> {
    fields_list
        .map(|field| {
            let mapped_field_type = match field.data_type() {
                DataType::Boolean => FieldType::Boolean,
                DataType::Time32(_)
                | DataType::Time64(_)
                | DataType::Duration(_)
                | DataType::Interval(_)
                | DataType::Int8
                | DataType::Int16
                | DataType::Int32
                | DataType::Int64 => FieldType::Int,
                DataType::UInt8 | DataType::UInt16 | DataType::UInt32 | DataType::UInt64 => {
                    FieldType::UInt
                }
                DataType::Float16 | DataType::Float32 | DataType::Float64 => FieldType::Float,
                DataType::Timestamp(_, _) => FieldType::Timestamp,
                DataType::Date32 | DataType::Date64 => FieldType::Date,
                DataType::Binary | DataType::FixedSizeBinary(_) | DataType::LargeBinary => {
                    FieldType::Binary
                }
                DataType::Utf8 => FieldType::String,
                DataType::LargeUtf8 => FieldType::Text,
                // DataType::List(_) => {}
                // DataType::FixedSizeList(_, _) => {}
                // DataType::LargeList(_) => {}
                // DataType::Struct(_) => {}
                // DataType::Union(_, _, _) => {}
                // DataType::Dictionary(_, _) => {}
                // DataType::Decimal128(_, _) => {}
                // DataType::Decimal256(_, _) => {}
                // DataType::Map(_, _) => {}
                _ => return Err(FieldTypeNotSupported(field.name().clone())),
            };

            Ok(FieldDefinition {
                name: field.name().clone(),
                typ: mapped_field_type,
                nullable: field.is_nullable(),
                source: SourceDefinition::Dynamic,
            })
        })
        .collect()
}
```

# Kafka Debezium
```
// Reference: https://debezium.io/documentation/reference/0.9/connectors/postgresql.html
pub fn map_type(schema: &DebeziumSchemaStruct) -> Result<FieldType, DebeziumSchemaError> {
    match schema.name.clone() {
        None => match schema.r#type.clone() {
            Value::String(typ) => match typ.as_str() {
                "int" | "int8" | "int16" | "int32" | "int64" => Ok(FieldType::Int),
                "string" => Ok(FieldType::String),
                "bytes" => Ok(FieldType::Binary),
                "float32" | "float64" | "double" => Ok(FieldType::Float),
                "boolean" => Ok(FieldType::Boolean),
                _ => Err(TypeNotSupported(typ)),
            },
            _ => Err(TypeNotSupported("Unexpected value type".to_string())),
        },
        Some(name) => match name.as_str() {
            "io.debezium.time.MicroTime"
            | "io.debezium.time.Timestamp"
            | "io.debezium.time.MicroTimestamp"
            | "org.apache.kafka.connect.data.Time"
            | "org.apache.kafka.connect.data.Timestamp" => Ok(FieldType::Timestamp),
            "io.debezium.time.Date" | "org.apache.kafka.connect.data.Date" => Ok(FieldType::Date),
            "org.apache.kafka.connect.data.Decimal" | "io.debezium.data.VariableScaleDecimal" => {
                Ok(FieldType::Decimal)
            }
            "io.debezium.data.Json" => Ok(FieldType::Json),
            _ => Err(TypeNotSupported(name)),
        },
    }
}
```

# gRPC
```
for (idx, v) in rec.values.iter().enumerate() {
    let typ = schema.fields[idx].typ;

    let v = v.value.as_ref().map(|v| match (v, typ) {
        (
            grpc_types::types::value::Value::UintValue(a),
            dozer_types::types::FieldType::UInt,
        ) => Ok(dozer_types::types::Field::UInt(*a)),

        (grpc_types::types::value::Value::IntValue(a), dozer_types::types::FieldType::Int) => {
            Ok(dozer_types::types::Field::Int(*a))
        }

        (
            grpc_types::types::value::Value::FloatValue(a),
            dozer_types::types::FieldType::Float,
        ) => Ok(dozer_types::types::Field::Float(OrderedFloat(*a))),

        (
            grpc_types::types::value::Value::BoolValue(a),
            dozer_types::types::FieldType::Boolean,
        ) => Ok(dozer_types::types::Field::Boolean(*a)),

        (
            grpc_types::types::value::Value::StringValue(a),
            dozer_types::types::FieldType::String,
        ) => Ok(dozer_types::types::Field::String(a.clone())),

        (
            grpc_types::types::value::Value::BytesValue(a),
            dozer_types::types::FieldType::Binary,
        ) => Ok(dozer_types::types::Field::Binary(a.clone())),
        (
            grpc_types::types::value::Value::StringValue(a),
            dozer_types::types::FieldType::Text,
        ) => Ok(dozer_types::types::Field::Text(a.clone())),
        (
            grpc_types::types::value::Value::BytesValue(a),
            dozer_types::types::FieldType::Json,
        ) => Ok(dozer_types::types::Field::Json(a.clone())),
        (
            grpc_types::types::value::Value::TimestampValue(a),
            dozer_types::types::FieldType::Timestamp,
        ) => Ok(
            chrono::NaiveDateTime::from_timestamp_opt(a.seconds, a.nanos as u32)
                .map(|t| {
                    dozer_types::types::Field::Timestamp(
                        chrono::DateTime::<chrono::Utc>::from_utc(t, chrono::Utc).into(),
                    )
                })
                .unwrap_or(dozer_types::types::Field::Null),
        ),
        (
            grpc_types::types::value::Value::DecimalValue(_),
            dozer_types::types::FieldType::Decimal,
        )
        | (
            grpc_types::types::value::Value::DateValue(_),
            dozer_types::types::FieldType::UInt,
        )
        | (
            grpc_types::types::value::Value::DateValue(_),
            dozer_types::types::FieldType::Date,
        )
        | (
            grpc_types::types::value::Value::PointValue(_),
            dozer_types::types::FieldType::Point,
        ) => Ok(dozer_types::types::Field::Null),
        (a, b) => Err(ConnectorError::InitializationError(format!(
            "data is not valid at index: {idx}, Type: {a:?}, Expected Type: {b}"
        ))),
    });
    values.push(v.unwrap_or(Ok(dozer_types::types::Field::Null))?);
}
```

# Delta Lake
```
pub fn map_schema_to_dozer<'a, I: Iterator<Item = &'a Field>>(
    fields_list: I,
) -> Result<Vec<FieldDefinition>, ObjectStoreSchemaError> {
    fields_list
        .map(|field| {
            let mapped_field_type = match field.data_type() {
                DataType::Boolean => FieldType::Boolean,
                DataType::Time32(_)
                | DataType::Time64(_)
                | DataType::Duration(_)
                | DataType::Interval(_)
                | DataType::Int8
                | DataType::Int16
                | DataType::Int32
                | DataType::Int64 => FieldType::Int,
                DataType::UInt8 | DataType::UInt16 | DataType::UInt32 | DataType::UInt64 => {
                    FieldType::UInt
                }
                DataType::Float16 | DataType::Float32 | DataType::Float64 => FieldType::Float,
                DataType::Timestamp(_, _) => FieldType::Timestamp,
                DataType::Date32 | DataType::Date64 => FieldType::Date,
                DataType::Binary | DataType::FixedSizeBinary(_) | DataType::LargeBinary => {
                    FieldType::Binary
                }
                DataType::Utf8 => FieldType::String,
                DataType::LargeUtf8 => FieldType::Text,
                // DataType::List(_) => {}
                // DataType::FixedSizeList(_, _) => {}
                // DataType::LargeList(_) => {}
                // DataType::Struct(_) => {}
                // DataType::Union(_, _, _) => {}
                // DataType::Dictionary(_, _) => {}
                // DataType::Decimal128(_, _) => {}
                // DataType::Decimal256(_, _) => {}
                // DataType::Map(_, _) => {}
                _ => return Err(FieldTypeNotSupported(field.name().clone())),
            };

            Ok(FieldDefinition {
                name: field.name().clone(),
                typ: mapped_field_type,
                nullable: field.is_nullable(),
                source: SourceDefinition::Dynamic,
            })
        })
        .collect()
}
```

**Comment by chubei** [comment]
> `Delta Lake` and `Object Store` share same way of type mapping

We can use one table `DataFusion`.

**Comment by chloeminkyung** [comment]
## Specifications for operators

### BinaryOperatorType

#### Comparison

##### `Equal` `=` & `Not Equal` `!=` & `Greater Than Equal` `>=` & `Less Than Equal` `<=`

|               | **_Right_** | **UInt** | **UInt128** | **Int** | **Int128** | **Float** | **Boolean** | **String** | **Text** | **Binary** | **Decimal** | **Timestamp** | **Date** | **Duration** | **Json** | **Point** | **Null** |
|---------------|-------------|----------|-------------|---------|------------|-----------|-------------|------------|----------|------------|-------------|---------------|----------|--------------|----------|-----------|----------|
| **_Left_**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **UInt**      |             | Boolean  |             | Boolean |            | Boolean   |             |            |          |            | Boolean     |               |          |              |          |           | Boolean  |
| **UInt128**   |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Int**       |             | Boolean  |             | Boolean |            | Boolean   |             |            |          |            | Boolean     |               |          |              |          |           | Boolean  |
| **Int128**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Float**     |             | Boolean  |             | Boolean |            | Boolean   |             |            |          |            | Boolean     |               |          |              |          |           | Boolean  |
| **Boolean**   |             |          |             |         |            |           | Boolean     |            |          |            |             |               |          |              |          |           |          |
| **String**    |             |          |             |         |            |           |             | Boolean    |          |            |             |               |          |              |          |           | Boolean  |
| **Text**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Binary**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Decimal**   |             | Boolean  |             | Boolean |            | Boolean   |             |            |          |            | Boolean     |               |          |              |          |           | Boolean  |
| **Timestamp** |             |          |             |         |            |           |             |            |          |            |             | Boolean       |          |              |          |           | Boolean  |
| **Date**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Duration**  |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Json**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Point**     |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Null**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           | Boolean  |

##### `Greater Than` `>` & `Less Than` `<`

|               | **_Right_** | **UInt** | **UInt128** | **Int** | **Int128** | **Float** | **Boolean** | **String** | **Text** | **Binary** | **Decimal** | **Timestamp** | **Date** | **Duration** | **Json** | **Point** | **Null** |
|---------------|-------------|----------|-------------|---------|------------|-----------|-------------|------------|----------|------------|-------------|---------------|----------|--------------|----------|-----------|----------|
| **_Left_**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **UInt**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **UInt128**   |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Int**       |             |          |             | Boolean |            | Boolean   |             |            |          |            |             |               |          |              |          |           | Boolean  |
| **Int128**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Float**     |             |          |             | Boolean |            | Boolean   |             |            |          |            |             |               |          |              |          |           | Boolean  |
| **Boolean**   |             |          |             |         |            |           | Boolean     |            |          |            |             |               |          |              |          |           |          |
| **String**    |             |          |             |         |            |           |             | Boolean    |          |            |             |               |          |              |          |           | Boolean  |
| **Text**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Binary**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Decimal**   |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Timestamp** |             |          |             |         |            |           |             |            |          |            |             | Boolean       |          |              |          |           | Boolean  |
| **Date**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Duration**  |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Json**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Point**     |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Null**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           | Boolean  |

#### Mathematical

|               | **_Right_** | **UInt** | **UInt128** | **Int** | **Int128** | **Float** | **Boolean** | **String** | **Text** | **Binary** | **Decimal** | **Timestamp** | **Date** | **Duration** | **Json** | **Point** | **Null** |
|---------------|-------------|----------|-------------|---------|------------|-----------|-------------|------------|----------|------------|-------------|---------------|----------|--------------|----------|-----------|----------|
| **_Left_**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **UInt**      |             | UInt     |             | Int     |            | Float     |             |            |          |            | Decimal     |               |          |              |          |           |          |
| **UInt128**   |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Int**       |             | Int      |             | Int     |            | Float     |             |            |          |            | Decimal     |               |          |              |          |           |          |
| **Int128**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Float**     |             | Float    |             | Float   |            | Float     |             |            |          |            | Decimal     |               |          |              |          |           |          |
| **Boolean**   |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **String**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Text**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Binary**    |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Decimal**   |             | Decimal  |             | Decimal |            | Decimal   |             |            |          |            | Decimal     |               |          |              |          |           |          |
| **Timestamp** |             |          |             |         |            |           |             |            |          |            |             | Int           |          |              |          |           |          |
| **Date**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Duration**  |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Json**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Point**     |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |
| **Null**      |             |          |             |         |            |           |             |            |          |            |             |               |          |              |          |           |          |

### UnaryOperator

#### `NOT` `!` & `AND` & `OR`

|             | **_Output_** | UInt | UInt128 | Int | Int128 | Float | Boolean | String | Text | Binary | Decimal | Timestamp | Date | Duration | Json | Point | Null |
|-------------|--------------|------|---------|-----|--------|-------|---------|--------|------|--------|---------|-----------|------|----------|------|-------|------|
| **_Input_** |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| UInt        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| UInt128     |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Int         |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Int128      |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Float       |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Boolean     |              |      |         |     |        |       | ✅       |        |      |        |         |           |      |          |      |       |      |
| String      |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Text        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Binary      |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Decimal     |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Timestamp   |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Date        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Duration    |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Json        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Point       |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Null        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       | ✅    |

#### `PLUS` `+` & `MINUS` `-`

|             | **_Output_** | UInt | UInt128 | Int | Int128 | Float | Boolean | String | Text | Binary | Decimal | Timestamp | Date | Duration | Json | Point | Null |
|-------------|--------------|------|---------|-----|--------|-------|---------|--------|------|--------|---------|-----------|------|----------|------|-------|------|
| **_Input_** |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| UInt        |              | ✅    |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| UInt128     |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Int         |              |      |         | ✅   |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Int128      |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Float       |              |      |         |     |        | ✅     |         |        |      |        |         |           |      |          |      |       |      |
| Boolean     |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| String      |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Text        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Binary      |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Decimal     |              |      |         |     |        |       |         |        |      |        | ✅       |           |      |          |      |       |      |
| Timestamp   |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Date        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Duration    |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Json        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Point       |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
| Null        |              |      |         |     |        |       |         |        |      |        |         |           |      |          |      |       |      |
