### ISSUE TITLE
API with `Order By` is returning wrong results

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#1230]
Using the following sample
https://github.com/getdozer/dozer-samples/tree/main/local-storage

```
curl -X POST  http://localhost:8080/trips/query \
  --header 'Content-Type: application/json' \
  --data-raw '{"$order_by": {"min_trip_time", "asc"}, "$limit":2}
```

I believe filter and limit and other constraints are not working when order_by is included.

**Comment by chubei** [comment]
The query is written wrong. It should be a `:` after `min_trip_time`. But it doesn't explain why `$limit` doesn't work. I'll check that.

Besides, do you think we should refuse to deserialize such query expressions?
