### ISSUE TITLE
Errors inside `init_telemetry_closure` is not printed to console

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1234]
## Describe the bug
Errors inside `init_telemetry_closure` is not printed to console

## Environment
- **Dozer version**: main
- **OS Version**: MacOS 13
- **Docker Compose Version(Optional)**: 

## To Reproduce

1. `dozer -c non-existent-file`

## Expected behavior
Error is printed to console.

## Logs
If applicable, add logs to help explain your problem.

**Comment by v3g42** [comment]
Fixed by https://github.com/getdozer/dozer/pull/1279
