### ISSUE TITLE
Import a YAML configuration from a URL as well as stdin 

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#1408]
Currently `dozer-config.yaml` can only be provided through local path.

Support
- URL path
- stdin
modes

```
dozer -c https://remote.url.com/dozer-config.yaml

cat dozer-config.yaml | dozer
```

**Comment by chubei** [comment]
@aaryaattrey Loading from URL is already implemented. We're missing loading from stdin here. We probably should do this in two steps:

1. Check if `dozer`'s stdin is a pipe.
2. If it's a pipe, read the whole stdin as the configuration file content.

You can have a look at code around https://github.com/getdozer/dozer/blob/main/dozer-cli/src/main.rs#L127.

My guess is that the check should be before `init_orchestrator` and `init_orchestrator` should get a extra parameter to determine if it reads from stdin.

The guess can be wrong. Let me know what you think after you read the code.
