### ISSUE TITLE
can't run the example in dozer-ingestion/examples/postgres/main.rs

### ISSUE THREAD

**Issue by ZzIsGod1019** [getdozer/dozer#1480]
## Describe the bug
I can't build this docker image because this path not exist config file and sql file 

![image](https://user-images.githubusercontent.com/18495344/234239368-cdfe6b2e-dce2-49cc-92f7-2b3a77ab191d.png)

**Comment by chubei** [comment]
Sorry that example is out of date. Please check our samples repo. https://github.com/getdozer/dozer-samples
