### ISSUE TITLE
Feature Request: Inference with ONNX Model as Custom SQL Function

### ISSUE THREAD

**Issue by abhishekmishragithub** [getdozer/dozer#1632]
## 📝 Description:

This is a proposal for a new feature in Dozer Core, to enhance the functionality by allowing users to utilize an ONNX model as a custom SQL function for scoring data in a streaming fashion. This feature would significantly benefit users who require real-time inference capabilities within their data processing pipelines.

## 🌟 Feature Details:

- **ONNX Model Integration:** Integrate the ONNX runtime into Dozer to support loading and executing ONNX models. This integration will enable users to leverage a wide range of pre-trained models from various popular machine learning frameworks.

- **Custom SQL Function:** Create a mechanism to define and register a custom SQL function using the configuration file. This function will serve as a bridge between the streaming data and the loaded ONNX model, allowing users to perform inference on the incoming data directly within their SQL queries.

- **Scalability and Performance:** Design the feature with scalability and performance in mind. Optimize the data processing pipeline to handle large volumes of streaming data efficiently, ensuring minimal latency and high throughput.

- **Error Handling and Fault Tolerance:** Leverage on Dozer error handling mechanisms to gracefully handle exceptions during the inference process.

- **Documentation and Examples:** Provide comprehensive documentation and examples to guide users on how to utilize this new feature effectively. The documentation should cover the integration steps, usage guidelines, and best practices for implementing and deploying the streaming inference pipeline.

## ✅ Benefits:

Users can leverage the power of ONNX models to perform real-time inference within their SQL queries. Users can seamlessly incorporate machine learning capabilities into their existing Dozer runtime without the need for extensive code changes or complex integrations. The feature allows users to select and use a wide range of pre-trained models.

**Comment by ibrahim-akrab** [comment]
I would like to take a stab at this, however, there is barely any documentation for dozer-core that I could find.

**Comment by chubei** [comment]
This boils down to add a variant to [`Expression`](https://github.com/getdozer/dozer/blob/main/dozer-sql/src/pipeline/expression/execution.rs#L25) in `dozer_sql`,  which can be further divided into 3 tasks.

1. Parsing and serializing. We should be able to build the new expression variant for ONNX from a sql function, if the function starts with a special prefix. [Example](https://github.com/getdozer/dozer/blob/main/dozer-sql/src/pipeline/expression/builder.rs#L393). We should be able to reproduce the sql function string using this expression. [Example](https://github.com/getdozer/dozer/blob/main/dozer-sql/src/pipeline/expression/execution.rs#L141). This is pretty straight forward.
2. Decide the ONNX function's output type from its input types. [Example](https://github.com/getdozer/dozer/blob/main/dozer-sql/src/pipeline/expression/execution.rs#L359).
3. Actually run the ONNX model with given inputs and return result to dozer. [Example](https://github.com/getdozer/dozer/blob/main/dozer-sql/src/pipeline/expression/execution.rs#L260).

**Comment by iho** [comment]
@ibrahim-akrab do you work on this task? I  think you need to post `/attempt` before starting because it's unclear who working on getting the bounty.

**Comment by ibrahim-akrab** [comment]
@iho yea sorry forgot the attempt thing. I am in fact working on it.
/attempt#1632

**Comment by ibrahim-akrab** [comment]
I am sorry, I got some urgent projects and I have to drop this. 
@iho, you can take it.

**Comment by Shubham8287** [comment]
@chubei, my understanding of the task is that we need to create a SQL function that allows users to interact with an ONNX model. Your previous comment helped me understand the implementation of the ONNX SQL function, but it seems to be focused on inference only. Could you provide more information on how users would be able to load their models into Dozer? Would it be creating a connector specifically for the ONNX format ? 
Additionally, it would be helpful if you could provide a sample configuration file (even if it's not finalized) to give me an idea of the user interaction and to help set expectations for the final end-to-end test case.

**Comment by chubei** [comment]
@Shubham8287

Model loading can happen in the expression variant building process, which comes to be at the first thought. There may be better ways. Feel free to suggest!

And for the configuration, I imagined something like
```yaml
...
sql: |
  SELECT onnx_fraud_detection(user.name, user.address) AS fraud FROM users;
```

But this is just me randomly talking so cloud be unreasonable. We look forward to hearing your thoughts!

**Comment by snork-alt** [comment]
We should add a section similar to the one below in the configuration file:
```
udf:
   onnx:
       is_fraudolent: ./models/mode_file 
```

This will create an `is_fraudolent()` SQL function, that, when invoked, will execute the model inference

**Comment by Shubham8287** [comment]
Thanks @chubei , @snork-alt. This is a great help for me to start on the task, I am done with the local setup, just kicking this off. :)

**Comment by digital-phoenix** [comment]
@snork-alt what's the current status of this issue?

**Comment by Ahmadkhan02** [comment]
@digital-phoenix its already been implemented
