### ISSUE TITLE
MySQL Connector

### ISSUE THREAD

**Issue by snork-alt** [getdozer/dozer#1670]
## Description
Implement MySQL connector for Dozer

## Details
The connector should use MySQL CDC similarly to the behavior of the PostgreSQL connector. All data changes from MySQL should be translated into Dozer Inserts, Deletes, or Updates. Connector should support resuming. 

## Deliverables
The implementation should come with comprehensive tests and a sample to be pushed to `dozer-samples` repo

**Comment by abcpro1** [comment]
/attempt https://github.com/getdozer/dozer/issues/1670
The PR currently claiming this issue looks like an AI generated joke. I think it's fair for me to work on it.

**Comment by snork-alt** [comment]
Thanks @abcpro1

**Comment by feliciien** [comment]
I'm still working on it @abcpro1 good luck
