### ISSUE TITLE
Get the wrong test result when running the tests

### ISSUE THREAD

**Issue by hi-rustin** [getdozer/dozer#1696]
## Describe the bug
If you change this test https://github.com/getdozer/dozer/blob/a5f49c43498617495b87cc36a9a7f62f95946ed1/dozer-sql/src/pipeline/expression/tests/comparison.rs#L543 to 
```rust
    let f = run_fct(
        "SELECT id FROM users WHERE id = '123'",
        schema.clone(),
        record.clone(),
    );
    assert_eq!(f, Field::Int(124));
```

The test still passed.

## Environment
- **Dozer version**: master branch
- **OS Version**: MacOS 13.4 (22F66)

## To Reproduce

1. Clone the repo 
2. Change the test 
3. Run it

## Expected behavior
It should fail.

**Comment by snork-alt** [comment]
@mediuminvader @chloeminkyung can you take a look ?

**Comment by mediuminvader** [comment]
@snork-alt @chloeminkyung  Found the problem, `run_fct` is meant to test just _Projection_, we need a proper test for _Selection_, `WHERE` clause is simply ignored.
