### ISSUE TITLE
the docker-compose example is missing

### ISSUE THREAD

**Issue by zodman** [getdozer/dozer#1825]
i want to see an example of a dozer in the docker-compose.yaml for copy/paste for get and ready to use.

and the version at hub.docker.com it is outupdate

**Comment by mediuminvader** [comment]
Hi @zodman, the team is working on a "Getting Started" for Docker Compose, it will be available in few days.
Meanwhile you can take a look at this sample https://github.com/getdozer/dozer-samples/tree/main/connectors/snowflake it's based on Snowflake, but it's easy adaptable.
Thank you for reporting about the DockerHub version, it will be updated ASAP. Currently our most recent docker image is on ECR at public.ecr.aws/getdozer/dozer:latest or public.ecr.aws/getdozer/dozer:dev

**Comment by tomas-dozer** [comment]
Hey zodman! I sent you an email with some links to our documentation. We would be happy to connect and have a quick chat with you. Here is our [Calendly](https://calendly.com/d/4jb-ryc-trn/meeting-with-dozer) in case you can find a time that suits you and you decide to schedule a meeting.

**Comment by tomas-dozer** [comment]
Here is also a video with an example https://www.youtube.com/watch?v=pVfyMfNrlD4
Best wishes!
