### ISSUE TITLE
REST `query` API ignores invalid JSON

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1852]
If user includes malformed JSON in the request body, it's just ignored and default query is executed. This causes confusion to users.

We need to answer several questions and define a new behaviour.

1. Do we execute query requests with no `content-type` header?
2. Do we execute query requests with `content-type` header that's not `application/json`?
3. If we do in 1 and 2, do we report malformed JSON body?
4. Does empty body count as malformed JSON?

My preference:

1. We execute query requests with no `content-type` header.
2. We don't execute query requests with `content-type` header that's not `application/json`.
3. We report malformed JSON body.
4. We don't treat empty body as malformed JSON and just execute the default query.

@getdozer/dozer-dev I'd like to hear your opinions.

**Comment by karolisg** [comment]
I agree on all your suggestions.

**Comment by Jesse-Bakker** [comment]
In general I always like going with the least surprising option and your suggestions would definitely be the least surprising to me.

**Comment by v3g42** [comment]
Makes sense.
