### ISSUE TITLE
Cleanup: Remove `Orchestrator` trait and Change `SimpleOrchestrator` methods to `async`

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1863]
- `SimpleOrchestrator` is the only implementor of `Orchestrator`. The trait is useless.
- Methods of `SimpleOrchestrator` are actually async. Currently we're using `Runtime::block_on` to switch between threads, which is confusing.

**Comment by MG190202** [comment]
This issue is resolved, please close this.
