### ISSUE TITLE
`push_events` flag is inconsistent between common and typed service. 

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#1871]
## Describe the bug

[OnEvent ](https://github.com/getdozer/dozer/blob/main/dozer-api/src/generator/protoc/generator/template/proto.tmpl#L36) is avaialble for CommonService even without this flag enabled. 

## Resolution
I suggest to make two changes. Make the default behavior yes since it has been around for a while. And make this flag effect both common and typed service.

**Comment by chubei** [comment]
I think this flag doesn't affect common service because the method signature is determined at compile time. It's not possible to have the same experience as typed services - the method is not even in the proto when disabled. We can check the flag at runtime and return error if it's not enabled
