### ISSUE TITLE
Create a Github Action that automatically labels PR as `doc-update-needed`

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1882]
Create a Github Action that runs on certain file changes and labels a PR as `doc-update-needed`.

The files to watch may include:

- Everything under `dozer-types/src/model` (the configuration file format)
- Everything related to command parameters (`dozer-cli/src/cli_types`)
- Customer facing proto files (`dozer-types/proto` and `proto.tmpl`)

**Comment by tungbq** [comment]
Hello, I would like to contribute to a CI task like this.
I've proposed the PR #1884 for this task. Can you please review it? Thanks!
