### ISSUE TITLE
Assign a unique ID to metrics on live server between application runs

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#1915]
When you run `dozer live` with different applications today, metrics are intermingled. We have this separation on cloud through deployment_id. 

On a local environment, I suggest adding that tag in https://github.com/getdozer/dozer/blob/main/dozer-cli/src/live/progress.rs

Expected behavior
- Repeat restarts should start counters from 0
- Run multiple applications one after another, metrics should stay isolated on the UI.

**Comment by chubei** [comment]
How about just delete data of older runs?

**Comment by chubei** [comment]
Did we solve the metrics problem @v3g42?

**Comment by v3g42** [comment]
Yes.
