### ISSUE TITLE
If Dozer is restarted during a running session, Dozer Live Ui is not updated

### ISSUE THREAD

**Issue by snork-alt** [getdozer/dozer#1964]
Repro steps:
- start dozer
- connect Live UI
- click start
- now ctrl^C on dozer binary and restart it
- go to Dozer Live UI and reconnect

Dozer live appears to be running, but it's not

**Comment by v3g42** [comment]
i think this is just a local development issue. React keeps the state.

**Comment by chubei** [comment]
Closing because there's no further response.
