### ISSUE TITLE
API behavior inconsitencies

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#1977]
Listing all the inconsistencies so we can track 

### gRPC services inconsistency
- [x] Naming difference between `typed` and `common`: `OnEvent` and `on_event`
- [x] Case is different between the responses: `typed` produces `CamelCase` and others produce `snake_case`

### Limit behavior
- [x] #1958

### Order behavior

- [x] If no order is specified, returned results should remain in a consistent order. Shall we automatically apply a order if nothing is specified ?

**Comment by chubei** [comment]
- Naming: we need to fix them.
- Limit: we should add a configuration option.
- Order: I think we should order records by ascending primary key when no filter is used. When filter is used, we don't apply order.

**Comment by supergi0** [comment]
Order:
1. How can we check for the primary key in the output? 
2. Are all output tables guaranteed to have a primary key?
3. Can we order them based on the first field in the map?

**Comment by chubei** [comment]
I checked the order implementation. It's in insertion order. I think it's reasonable.

**Comment by supergi0** [comment]
So it is ordered based on `__dozer_record_id`, therefore no need to change?

**Comment by chubei** [comment]
`__dozer_record_id` and insertion order have some subtle difference:

If you update a record, its `__dozer_record_id` stays the same but in insertion order it goes to last.

Yes I think no need to change.

**Comment by supergi0** [comment]
Can we sort based on `__dozer_record_id` then, as I can think of some scenarios where I update few top records and want to see the same records again on the top?

**Comment by chubei** [comment]
Our current implementation don't support sorting based on `__dozer_record_id` now. I don't think the effort is worth it.
