### ISSUE TITLE
If gRPC/rest port are changed in the config, Dozer Live stops working

### ISSUE THREAD

**Issue by snork-alt** [getdozer/dozer#1990]
It's probably due to the fact Dozer Live UI still tries to reach gRPC and RESTR servers on default ports.
We should pass those ports in teh URL when we launch dozer live

**Comment by supergi0** [comment]
Tried testing this,
1. `dozer live` does not respect the API port defined in the yaml file, whereas `dozer run` does.
2. `dozer live` will start rest and grpc on default ports i.e. 8080 and 50051 even after specifying different ports.
3. Hence I did not see Live UI to stop working as it was never accessing the new ports.

**Comment by snork-alt** [comment]
Try running something else on those ports to block dozer from binding to them

**Comment by chubei** [comment]
Closing because this issue doesn't exist.
