### ISSUE TITLE
Dozer Live: Api Security JWT config is not working in live version

### ISSUE THREAD

**Issue by duonganhthu43** [getdozer/dozer#1994]
**Input:** 
add API security config in `dozer-config.yaml`
```
api:
  api_security: !Jwt COv9gMj9L12CDFT2zI5o
```

**Expected:** 
Access Api endpoint without `Authorization` header should return `Unauthorized`

**Actual:** 
Api endpoint still return data without checking Authorization

**Comment by chubei** [comment]
@v3g42 is this by design?
