### ISSUE TITLE
[Docs] broken, embedded-in-docs weblinks

### ISSUE THREAD

**Issue by johnnyutahh** [getdozer/dozer#2038]
summary:

1. `404 Not Found` broken weblinks
2. is there a good place to read/learn more about "connector frameworks"?

details:

1. several `404 Not Found` broken weblinks...

from https://github.com/getdozer :

https://getdozer.io/docs/dozer/architecture
https://getdozer.io/docs/reference/api/security
https://getdozer.io/docs/dozer/comparision

from https://github.com/getdozer/dozer-samples :

https://getdozer.io/docs/sql/introduction
https://getdozer.io/docs/dozer/architecture
https://getdozer.io/docs/configuration/connectors

Given how quickly I found the above (in about 5 mins), I suspect there's more.

suggestions (often easier said than done, of course; I've been there several times myself 🤓):

- employ weblink checkers (I've not used 'em, but I bet there's convenient ones out there)
- create fewer doc sources, less things to break
- minimize the number of "docs layout/subsystem" redos/re-spins

none of these points are novel, of course.

2. "connector(s) framework"

There's also an unlinked mention of "connector(s) framework" somewhere I (think) I saw, and I'd like to learn more about that. Is there a place one can point me to, or is https://getdozer.io/docs/configuration/connectors (or it's substitute) _the_ place to learn about the "framework" part of "connectors"?

**Comment by siddhakdak** [comment]
working on it

**Comment by supergi0** [comment]
Hey, thanks for pointing it out. The documentation was recently changed, links should be fixed now.

You may check the following links for more information on connectors.
- docs: https://getdozer.io/docs/category/data-sources
- samples: https://github.com/getdozer/dozer-samples/tree/main/connectors
- blog: https://getdozer.io/blog/ ( has blogs on some connectors, more will be soon added!)
