### ISSUE TITLE
REST & gRPC: Streaming filter using query expression

### ISSUE THREAD

**Issue by duonganhthu43** [getdozer/dozer#209]
Streaming only exists in gRPC. For each endpoint input from the orchestrator. We have 4 streaming events to subscribe

- on_insert
- on_update
- on_delete
- on_schema_change

1. Each event is going to take a filter expression as input to narrow down the messages the client received
2. Filter input should have the same structure as `Filter Expression` inside `Query Expression` in cache
3. When the event is triggered, apply filter to decide whether or not the server should notify the client

**Comment by chubei** [comment]
Outdated
