### ISSUE TITLE
Postgres resuming

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#2279]
We removed postgres resuming in one of the iterations, however most of the code is kept unchanged. It should be easy to enable it again.

**Comment by karolisg** [comment]
Enabling postgres replication. Current flow design chart is [here(https://link.excalidraw.com/readonly/zTWxeRYi42ESRMjs6yCG)

<img width="780" alt="Screenshot 2024-01-02 at 14 51 21" src="https://github.com/getdozer/dozer/assets/1695346/7f085822-2d40-435c-ad67-933e75b96f28">

**Comment by karolisg** [comment]
Related issue to postgres continue ingestion:
https://github.com/getdozer/dozer/issues/2287
