### ISSUE TITLE
Ethereum connector faiilng when there are multiple sources. 

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#648]
## Describe the bug
eth e2e test is panicking, with code in https://github.com/getdozer/dozer/pull/644,

## Environment
E2E test cases
## To Reproduce

```
rm -r .dozer; cargo build --bin dozer && cargo run --bin dozer-tests -- eth 
```

```
run rm -r .dozer; cargo build --bin dozer && cargo run --bin dozer-tests -- eth 
▹▹▹▹▹ eth_logs: Count: 2804
▹▹▹▹▹ eth_stats: Count: 2804                                                                                                                                                         2023-01-17T11:09:39.222736Z ERROR panicked at 'name is expected', dozer-ingestion/src/connectors/ethereum/helper.rs:85:10
thread 'main' panicked at 'Service "./target/debug/dozer" "--config-path" "/Users/chubei/dozer/dozer-tests/src/e2e_tests/cases/eth/dozer-config.yaml" is expected to run in background, but it exited with status exit status: 1', dozer-tests/src/e2e_tests/runner/mod.rs:111:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by v3g42** [comment]
@karolisg do you know why this could be happening ?

**Comment by karolisg** [comment]
From error, I see that topic name is missing in log. I will investigate more.

**Comment by v3g42** [comment]
@chubei @karolisg Some context. 
https://github.com/getdozer/dozer/blob/main/dozer-ingestion/src/connectors/ethereum/tests/helper.rs#L107

Basically this function is a recursive call. 

So we need to do two things.
Order the recursive calls so that we get the data in order.
Secondly between calls, we have to deduplicate as we might get some duplciates between calls. So use a Hashset to keep ids in memory.

One more thing we should probably do. In the context of eth , clear separation is a `block_no`

so we can use `block_no` like an `epoch` or in the context of a connector, `transaction_id`

**Comment by v3g42** [comment]
I am not sure if this will fix the issue though. Will have to be tested.

**Comment by v3g42** [comment]
@karolisg @chubei  https://github.com/getdozer/dozer/pull/652
What I described earlier is unrelated looks like.

We just had to decode the event only if it matches with a contract address configured.

**Comment by karolisg** [comment]
@chubei If everything works fine, lets close this issue
