### ISSUE TITLE
GRPC doesnt support decimal

### ISSUE THREAD

**Issue by karolisg** [getdozer/dozer#695]
## Describe the bug
Current implementation of protoc files generator uses double for decimal numbers.
Ref - https://github.com/getdozer/dozer/blob/09d84ac50b2469546d1afcec987a14f6f63fd715/dozer-api/src/generator/protoc/generator.rs#L241

**Comment by chubei** [comment]
It looks like protobuf doesn't support decimal. Do you have a solution in mind?

**Comment by karolisg** [comment]
Maybe we can encode it as a struct. Like in debezium https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-decimal-types

**Comment by chubei** [comment]
I see! Like create a `message Decimal`?

**Comment by karolisg** [comment]
Yeah. Something like this
```
{
  value: i64,
  scale: u8
}
```

**Comment by chubei** [comment]
Agreed. @snork-alt @v3g42 @mediuminvader what do you think?

**Comment by mediuminvader** [comment]
There is a 5 years discussion on this on the [protobuf repo](https://github.com/protocolbuffers/protobuf/issues/4406).

Something like Debezium should work, but I'd like to understand better what will be the impact of this.
for instance, if we decide at some point to refactor this, all the user APIs will breaks?

**Comment by chubei** [comment]
> Something like Debezium should work, but I'd like to understand better what will be the impact of this. for instance, if we decide at some point to refactor this, all the user APIs will breaks?

Great point! TBH I'm not sure about the compatibility implications. I just thought it's something we should support before going to customers.

**Comment by auterium** [comment]
Maybe considering the layout of [rust-decimal](https://github.com/paupino/rust-decimal)? This crate is widely used and has support for some PG adapters already as well as `serde`, `borsh`, and other binary formats, so it might ease compatibility.

Alternatively, a message that wraps `bytes` + a format enum could allow for plenty of flexibility for future formats. I.e.
```
message RustDecimal {
  enum Encoding {
    STRING = 0;
    C_REPR = 1;
    BORSH = 2;
  }

  Encoding encoding = 1;
  bytes data = 2;
}
```

**Comment by v3g42** [comment]
Lets encode `rust-decimal` as a `Message` as we already use that type in our code base. 
https://github.com/getdozer/dozer/blob/main/dozer-types/Cargo.toml#L12
