### ISSUE TITLE
feat: support cross join

### ISSUE THREAD

**Issue by xudong963** [getdozer/dozer#736]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I'll do it.

**Comment by mediuminvader** [comment]
Hi @xudong963, 

thanks for your request. Can you give some more details on your use case?
Currently we're more focused on implementing LEFT and RIGHT JOIN.

**Comment by xudong963** [comment]
No use case, I just want to do some features to be familiar with dozer

**Comment by xudong963** [comment]
Close the issue to avoid conflict with @mediuminvader 's work.
