### ISSUE TITLE
refactor: Generate the PK or store the entire record in the JOIN index if the PK is not defined

### ISSUE THREAD

**Issue by mediuminvader** [getdozer/dozer#781]
## Describe the bug
If a record without a PK in the schema reach the JOIN the output records are randomly joined

## To Reproduce
This should not happen as every source is required to have or generate a PK

## Expected behavior
The PK is required by streaming join as it is used as a lookup key in the processor indexes.
edit:
If a PK is not defined, use the entire record as a PK and store in the JOIN index.
In case of append only sources, the PK can be generated.

**Comment by chubei** [comment]
Should we generate PK if JOIN is needed but PK is not available?

**Comment by mediuminvader** [comment]
@chubei I have updated the desctiption.

Generating the PK doesn't allow to execute deletes and updates, but your strategy will be good for append only streams.
We'll follow 2 approaches: full record for updatable sources without PK, generated PK for append only sources without PK.

**Comment by mediuminvader** [comment]
#817
