### ISSUE TITLE
Cache Operation fails for Primary Key mismatching the SQL

### ISSUE THREAD

**Issue by mediuminvader** [getdozer/dozer#876]
## Describe the bug
When there is a GROUP BY and fields don't match with primary Key in cache, Cache will throw an UpdateError. 
Related to above, Cache Inserts fail when primary key is not consistent with the select in SQL.

**Comment by chubei** [comment]
Is this solved now? @mediuminvader

**Comment by mediuminvader** [comment]
We should decide how to manage the error.

**Comment by chubei** [comment]
I thought we introduced a validation step to detect this case. You mean the validation is not good enough to detect all illegal primary keys?

**Comment by mediuminvader** [comment]
then it's solved.
