### ISSUE TITLE
Implement unit test for Postgres connector

### ISSUE THREAD

**Issue by mediuminvader** [getdozer/dozer#889]

**Comment by karolisg** [comment]
Additionally to existing tests, I think we also need to have such tests:

- [ ] Continue ingestion from last checkpoint
- [ ] Create publication slot
- [ ] Fail to drop publication slot
- [ ] Fail to create publication slot
- [ ] Snapshoting - sync tables
- [ ] Replicator - continue replication from middle of transaction (when the last checkpoint `seq_no` is not 0 and that transaction contains more than one message)
