### ISSUE TITLE
`RwCache` unnecessarily invokes `get_schema_and_indexes_from_record()` for each record

### ISSUE THREAD

**Issue by snork-alt** [getdozer/dozer#935]
Every time a record is inserted, deleted, or updated the `RWCache` invokes `self.get_schema_and_indexes_from_record(&record)?` unnecessarily, causing the sink to be much slower. 
`

**Comment by chubei** [comment]
Yes this is something I've always wanted to fix. Because we guarantee there's only one schema in cache now, we don't need to query the schema based on schema identifier, and we should remove schema identifier from record. Do you have a measurement of how much the slowdown is?

**Comment by snork-alt** [comment]
I can gather it, but it is quite substantial. I saw for every record there is a bincode deserialization
