### ISSUE TITLE
Introduce Nested Record structure in dozer types

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#956]
- Add Record as a Field Type. 
- (or) Array type

I am wondering if we can remove Bson altogether and just stick with Binary. 

```rust
pub const DATE_FORMAT: &str = "%Y-%m-%d";
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, PartialOrd, Ord)]
pub enum Field {
    UInt(u64),
    Int(i64),
    Float(OrderedFloat<f64>),
    Boolean(bool),
    String(String),
    Text(String),
    Binary(Vec<u8>),
    Decimal(Decimal),
    Timestamp(DateTime<FixedOffset>),
    Date(NaiveDate),
    Bson(Vec<u8>),
    Null,
}
```

**Comment by chubei** [comment]
`Bson` is for postgres `JSONB` data type last time I asked @snork-alt

**Comment by revskill10** [comment]
Do you have ETA for this feature ? I'm using JSONB and Array Type for our database and got error `__jsonb not supported` on array jsonb type.

**Comment by chloeminkyung** [comment]
> Do you have ETA for this feature ? I'm using JSONB and Array Type for our database and got error `__jsonb not supported` on array jsonb type.

Hi @revskill10 , we have nested type support on its way as our planned pipeline - will inform you on this thread when it's ready
